pub mod a_variables;
pub mod b_functions;
pub mod c_simple_types;
pub mod d_control_flow_strings;
pub mod e_ownership_references;
pub mod f_structs_traits;
pub mod g_collections_enums;
pub mod h_closures_threads;
pub mod i_idiomatic;
